# Source: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
# Automatically generates releases on new version tag

# Example trigger:
# git tag v0.1.0
# git push
# git push origin --tags

# TODO: Change 'pip install git+https://github.com/AppImageCrafters/appimage-builder.git' to 'pip install appimage-builder'
# TODO: once 'https://github.com/AppImageCrafters/appimage-builder/issues/324' is fixed

name: Build releases

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build:
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller --icon=packaging/icons/icon_512x512.png -F -w -n ChimpStackr src/run.py &&
                cd dist/ &&
                zip -r9 ChimpStackr ChimpStackr.app/
            OUT_FILE_NAME: ChimpStackr.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller --icon=packaging/icons/icon.ico -F -w --add-data "packaging/icons/icon_512x512.png;packaging/icons" -n ChimpStackr src/run.py
            OUT_FILE_NAME: ChimpStackr.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: ubuntu
            CMD_BUILD: >
              pip install git+https://github.com/AppImageCrafters/appimage-builder.git &&
              appimage-builder --skip-tests &&
              mkdir dist/ &&
              mv *.AppImage dist/
            OUT_FILE_NAME: ChimpStackr-latest-x86_64.AppImage
            ASSET_MIME: application/ChimpStackr
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v1
      with:
        name: release_url
    - name: Get Release File Name & Upload URL
      id: get_release_info
      shell: bash
      run: |
        value=`cat release_url/release_url.txt`
        echo ::set-output name=upload_url::$value
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./dist/${{ matrix.OUT_FILE_NAME}}
        asset_name: ${{ matrix.OUT_FILE_NAME}}
        asset_content_type: ${{ matrix.ASSET_MIME}}
